import aiosqlite
import json
from config import DATABASE_PATH

async def get_db():
    return await aiosqlite.connect(DATABASE_PATH)

async def init_db():
    db = await get_db()
    await db.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            telegram_id INTEGER UNIQUE NOT NULL,
            username TEXT,
            full_name TEXT,
            phone TEXT,
            country TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS categories (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT,
            sort_order INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            category_id INTEGER,
            name TEXT NOT NULL,
            description TEXT,
            benefits TEXT,
            usage_info TEXT,
            full_info TEXT,
            price REAL NOT NULL,
            image_url TEXT,
            in_stock INTEGER DEFAULT 1,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (category_id) REFERENCES categories(id)
        );

        CREATE TABLE IF NOT EXISTS package_options (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            price REAL NOT NULL,
            FOREIGN KEY (product_id) REFERENCES products(id)
        );

        CREATE TABLE IF NOT EXISTS cart_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            telegram_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            package_option_id INTEGER,
            quantity INTEGER DEFAULT 1,
            UNIQUE(telegram_id, product_id, package_option_id)
        );

        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            telegram_id INTEGER NOT NULL,
            full_name TEXT,
            phone TEXT,
            address TEXT,
            delivery_method TEXT,
            delivery_fee REAL DEFAULT 0,
            subtotal REAL NOT NULL,
            total REAL NOT NULL,
            payment_method TEXT,
            payment_status TEXT DEFAULT 'pending',
            order_status TEXT DEFAULT 'pending',
            items_json TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (telegram_id) REFERENCES users(telegram_id)
        );

        CREATE TABLE IF NOT EXISTS faqs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            question TEXT NOT NULL,
            answer TEXT NOT NULL,
            sort_order INTEGER DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS enquiries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            telegram_id INTEGER NOT NULL,
            message TEXT NOT NULL,
            status TEXT DEFAULT 'open',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS broadcasts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            message TEXT NOT NULL,
            sent_to INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT
        );
    """)
    await db.commit()
    await db.close()

async def seed_demo_data():
    db = await get_db()
    count = await db.execute("SELECT COUNT(*) FROM categories")
    row = await count.fetchone()
    if row[0] > 0:
        await db.close()
        return

    await db.execute(
        "INSERT INTO categories (name, description, sort_order) VALUES (?, ?, ?)",
        ("Fat Loss", "Prescription peptides and compounds for weight management, metabolic health, and body composition", 1)
    )

    products = [
        {
            "name": "Tirzepatide 20mg (Mounjaro / Zepbound)",
            "benefits": "Dual-pathway injectable for enhanced appetite control and metabolic support.\nSupports appetite regulation and portion control.\nHelps improve blood sugar response after meals.\nMay support meaningful fat loss and metabolic health.",
            "usage": "Once-weekly subcutaneous injection.",
            "price": 179.00,
            "desc": "Tirzepatide is a prescription injectable used in medically supervised weight management and type 2 diabetes care, where appropriate. It works through two hormone pathways involved in appetite, digestion, and glucose control, helping the body respond more efficiently to food.\n\nIt is often selected by clients who want a refined, clinical approach to body recomposition. The appeal lies in its ability to support appetite control, improve consistency with nutrition, and complement a structured fat-loss plan under professional guidance.",
            "full_benefits": "Appetite regulation: Helps reduce hunger and makes smaller portions feel more manageable.\nGlucose support: Encourages a more stable blood sugar response after meals.\nFat-loss assistance: May contribute to reductions in weight, waist circumference, and broader metabolic health markers.\nConvenient schedule: Once-weekly dosing supports long-term adherence.",
            "dosage": "Begin with 2.5mg once weekly for 4 weeks.\nIncrease to 5mg once weekly if well tolerated.\nFurther increases may be made gradually every 4 weeks, according to response and tolerance.\nThe maximum commonly used dose is 15mg once weekly, under medical supervision.",
            "how_to_use": "Inject once weekly as directed by a qualified healthcare professional.\nAdminister into the abdomen, thigh, or upper arm, rotating sites regularly.\nStarting at a lower dose and progressing gradually can help improve comfort and tolerance.\nBest results are typically achieved alongside protein-focused nutrition, hydration, and resistance training.",
            "customers_know": "This is a prescription product and should only be used within a medically supervised program.\nIt is not suitable for everyone, particularly those with specific thyroid or pancreas-related histories.\nCommon early effects can include nausea, reduced appetite, constipation, reflux, and mild fatigue.\nSmaller meals and lower-fat food choices may improve comfort, especially in the first few weeks.\nIndividual outcomes vary depending on dose, duration, and lifestyle factors.",
            "faqs": "How long until I see results?\nMany clients notice appetite changes within the first few doses, while visible changes in body composition usually take several weeks to develop. Consistent nutrition, sleep, and training remain important.\n\nWhat are the common side effects?\nFrequently reported effects include nausea, reduced appetite, constipation, reflux or burping, mild stomach discomfort, and occasional fatigue, particularly when starting or increasing the dose.\n\nHow do I store it?\nRefrigerate at 2-8C. Do not freeze. Keep protected from direct sunlight and heat.\n\nCan I stack this with other fat-loss supports?\nIt may be combined with selected metabolic and lifestyle supports, but any combination should be chosen carefully with professional guidance to ensure suitability and safety.\n\nIs this suitable for beginners?\nIt may be suitable for beginners who meet clinical criteria and are closely supervised. A thorough screening process is essential before starting.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Retatrutide 10mg",
            "benefits": "Multi-receptor, next-generation injectable for intensive fat-loss programmes.\nSupports powerful appetite regulation and portion control.\nHelps improve metabolic efficiency and glucose handling.\nMay drive significant fat loss, including visceral and subcutaneous fat.",
            "usage": "Once-weekly subcutaneous injection.",
            "price": 180.00,
            "desc": "Retatrutide is an advanced, multi-receptor injectable therapy designed for medically supervised weight management and metabolic optimisation. It targets several gut hormone pathways involved in appetite, energy balance, and glucose regulation, offering a sophisticated approach to fat loss and metabolic health.\n\nIt is often chosen by clients seeking a next-generation option when simple lifestyle changes or single-hormone treatments are not enough. The focus is on clinically guided body recomposition, improved adherence to nutrition plans, and deeper support for metabolic function.",
            "full_benefits": "Appetite regulation: Helps reduce hunger and food preoccupation, allowing more controlled portions and fewer cravings.\nMetabolic support: Assists the body in handling glucose and energy more efficiently, complementing nutrition and training strategies.\nComprehensive fat-loss assistance: May support reductions in both deep visceral fat and surface subcutaneous fat over time.\nOnce-weekly schedule: A convenient dosing rhythm that fits well into structured programs.",
            "dosage": "Typically initiated at a low introductory dose once weekly to assess tolerance.\nGradual dose increases are made under professional supervision, usually every few weeks.\nThe final maintenance dose is personalised based on response, side-effect profile, and overall goals.\nAll dosing decisions should be made and monitored by a qualified healthcare professional.",
            "how_to_use": "Inject once weekly as directed by a medical provider.\nAdminister into the abdomen, thigh, or upper arm, rotating sites to maintain skin comfort.\nStart low and titrate slowly to minimise digestive and systemic side effects.\nFor best outcomes, pair with a structured nutrition plan, adequate protein, hydration, and resistance training.",
            "customers_know": "Retatrutide is intended for use within a medically supervised program; it is not a casual weight-loss product.\nSuitability depends on individual health status, medical history, and current medications.\nCommon early effects can include nausea, reduced appetite, fullness, digestive changes (constipation or diarrhoea), reflux, and fatigue.\nEating smaller meals, moderating fat intake, and maintaining hydration can improve comfort during dose escalation.\nResults are influenced by lifestyle, dose progression, duration of use, and individual metabolic response.",
            "faqs": "How long until I see results?\nMany clients notice appetite changes and improved control within the first few weeks. Visible changes in weight, waist circumference, and body composition usually build progressively over several weeks to months, especially when paired with a consistent plan.\n\nWhat are the common side effects?\nCommonly reported effects include nausea, altered appetite, digestive changes (constipation, diarrhoea, or bloating), reflux, burping, and mild fatigue, particularly when starting or increasing the dose. These often settle as the body adapts.\n\nHow do I store it?\nRefrigerate at 2-8C. Do not freeze. Keep protected from direct sunlight and heat, and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nIt may be used alongside selected peptides and metabolic supports, but combinations must be chosen with care. Stacking should only be done under professional guidance to avoid overlap, excessive side effects, or unnecessary risk.\n\nIs this suitable for beginners?\nIt can be suitable for appropriately screened beginners who require a more intensive medical approach to fat loss. A thorough assessment and ongoing monitoring are essential before and during use.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Semaglutide 10mg (Ozempic / Wegovy)",
            "benefits": "Gold-standard GLP-1 therapy for clinically guided appetite and weight management.\nSupports appetite reduction and control of food cravings.\nHelps improve blood sugar response after meals.\nMay assist with clinically meaningful weight and waist reduction.",
            "usage": "Once-weekly subcutaneous injection.",
            "price": 179.00,
            "desc": "Semaglutide is a prescription injectable used in medically supervised weight management and type 2 diabetes care, where appropriate. It acts on the GLP-1 pathway, a key hormone involved in appetite regulation, digestion, and glucose control, helping the body manage food intake and post-meal blood sugar more effectively.\n\nClients often choose semaglutide when they want a proven, clinically guided route to fat loss with strong appetite control support. It is widely recognised for its ability to make eating less feel more sustainable, especially when combined with a structured nutrition and training plan.",
            "full_benefits": "Appetite reduction: Helps decrease hunger and reduce \"food noise,\" making smaller portions more sustainable.\nGlucose support: Promotes a more stable blood sugar response after meals.\nWeight-loss assistance: May support reductions in body weight, waist circumference, and metabolic risk markers.\nConvenient weekly dosing: Once-weekly injections support long-term adherence.",
            "dosage": "Typically initiated at a low starting dose once weekly to assess tolerance.\nGradual dose increases are made over several weeks, according to clinical guidance and response.\nThe target maintenance dose is personalised based on goals, side-effect profile, and overall progress.\nAll dosing decisions should be made by, and monitored with, a qualified healthcare professional.",
            "how_to_use": "Inject once weekly as directed by a medical provider.\nAdminister into the abdomen, thigh, or upper arm, rotating injection sites regularly.\nStarting at a lower dose and titrating slowly can help minimise digestive side effects.\nFor optimal outcomes, pair with protein-focused nutrition, hydration, and resistance training.",
            "customers_know": "Semaglutide is a prescription product intended for use within a medically supervised program.\nSuitability depends on individual medical history, current medications, and metabolic status.\nCommon early effects can include nausea, reduced appetite, constipation or diarrhoea, reflux, and fatigue.\nEating smaller meals, moderating dietary fat, and maintaining hydration can improve comfort as doses are escalated.\nResults are influenced by lifestyle, dose progression, and duration of use; this is not a quick fix but a structured therapy.",
            "faqs": "How long until I see results?\nMany clients notice appetite changes within the first few weeks, while visible changes in weight and waist circumference typically build progressively over several weeks to months, especially when lifestyle measures are in place.\n\nWhat are the common side effects?\nCommonly reported effects include nausea, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue, particularly during the early phase or when increasing the dose. These often settle as the body adapts.\n\nHow do I store it?\nRefrigerate at 2-8C. Do not freeze. Keep protected from direct sunlight and heat, and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nIt may be paired with selected peptides and metabolic supports, but stacking should only be done under professional guidance to avoid unnecessary overlap, side effects, or risk.\n\nIs this suitable for beginners?\nIt can be suitable for appropriately screened beginners who require structured medical support for weight management. A thorough assessment and regular follow-up are essential.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Cagrilintide 5mg",
            "benefits": "Long-acting amylin analogue focused on deep satiety and meal-volume control.\nSupports strong appetite regulation and increased satiety.\nHelps reduce overall food intake and meal volume over time.\nMay assist with weight reduction and metabolic health in structured programs.",
            "usage": "Once-weekly subcutaneous injection, with gradual dose titration.",
            "price": 119.00,
            "desc": "Cagrilintide is a long-acting amylin analogue used in medically supervised weight-management and metabolic programmes. By activating central amylin-calcitonin receptors, it helps enhance satiety, reduce food intake, and slow gastric emptying, supporting sustained caloric reduction.\n\nClients typically choose cagrilintide when they want a more advanced, appetite-first strategy, either as monotherapy or alongside GLP-1-based therapies. It is valued for its ability to address appetite and \"food noise\" from a different pathway, which can be especially helpful when single-pathway fat-loss treatments plateau or are less well tolerated.",
            "full_benefits": "Enhanced satiety: Helps increase feelings of fullness and reduce the desire to eat between meals.\nReduced food intake: May support lower meal volume and overall caloric intake in a structured plan.\nMetabolic support: Can contribute to weight reduction and improvements in metabolic parameters when used within clinical programmes.\nDistinct pathway: Acts via the amylin axis, making it complementary to GLP-1 therapies such as semaglutide in selected cases.",
            "dosage": "Commonly initiated at a low once-weekly dose (for example, around 0.3mg) to assess tolerance, then titrated upward.\nDose adjustments are typically made every few weeks based on appetite response, side-effect profile, and overall progress.\nThe maintenance dose is individualised; all dosing decisions should be made and monitored by a qualified healthcare professional.",
            "how_to_use": "Inject once weekly as directed by a medical provider.\nAdminister into the abdomen, thigh, or upper arm, rotating injection sites regularly.\nBegin at a lower dose and titrate gradually to help minimise digestive and systemic side effects.\nAlign use with a structured nutrition plan, adequate protein, hydration, and resistance training for best outcomes.",
            "customers_know": "Cagrilintide is an investigational / advanced metabolic therapy, intended for use in medically supervised programmes; it is not a casual weight-loss product.\nSuitability depends on individual health status, medical history, and current medications, including other anti-obesity agents.\nCommon early effects may include nausea, increased fullness, reduced appetite, digestive changes (constipation, diarrhoea, bloating), and mild fatigue.\nSmaller meals, moderated dietary fat, and maintained hydration can improve comfort during dose escalation.\nResults are influenced by lifestyle, dose progression, and duration of therapy; it is designed for sustained, programme-based use rather than short-term quick fixes.",
            "faqs": "How long until I see results?\nMany clients notice changes in appetite and satiety within the first few weeks, while visible weight and waist changes usually build progressively over several weeks to months, especially when combined with consistent nutrition and training.\n\nWhat are the common side effects?\nFrequently reported effects in trials and clinical use include nausea, increased fullness, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue, particularly during initiation or dose increases. These effects often lessen as the body adapts.\n\nHow do I store it?\nRefrigerate at 2-8C. Do not freeze. Keep protected from direct sunlight and heat and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nCagrilintide may be combined with selected GLP-1 therapies (for example, semaglutide) and other metabolic supports, but stacking must be carefully designed and supervised to avoid overlap, excessive appetite suppression, or side effects.\n\nIs this suitable for beginners?\nIt can be suitable for appropriately screened beginners who require intensive appetite and weight-management support, but it should only be introduced after thorough assessment and with ongoing monitoring.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Survodutide 5mg",
            "benefits": "Dual GLP-1 / glucagon-axis injectable with a focus on visceral and liver fat reduction.\nSupports advanced appetite regulation and reduced food cravings.\nHelps improve metabolic efficiency and glucose handling.\nMay assist with significant weight and waist reduction in structured programmes.",
            "usage": "Once-weekly subcutaneous injection, with guided dose titration.",
            "price": 139.00,
            "desc": "Survodutide is a next-generation injectable therapy designed for medically supervised weight management and metabolic optimisation. It combines activity at multiple gut-hormone pathways involved in appetite, energy balance, and glucose regulation, offering a sophisticated approach to fat loss and metabolic health.\n\nClients typically consider survodutide when they need more intensive support than lifestyle alone, or when earlier-generation therapies have produced only partial results. It is positioned as part of a structured programme that addresses appetite, metabolic resilience, and long-term adherence to nutrition and training plans.",
            "full_benefits": "Appetite regulation: Helps reduce hunger and \"food noise,\" supporting smaller portions and fewer unplanned snacks.\nMetabolic support: Assists the body in handling glucose and energy more efficiently, complementing nutrition and resistance training.\nComprehensive fat-loss assistance: May support reductions in both visceral (deep) and subcutaneous (surface) fat over time.\nConvenient schedule: Once-weekly dosing fits well into high-structure, busy lifestyles.",
            "dosage": "Typically initiated at a low introductory dose once weekly to assess tolerance.\nDose increases are made progressively every few weeks under medical supervision.\nThe maintenance dose is personalised based on appetite response, body-composition changes, side-effect profile, and overall goals.\nAll dosing decisions should be made and monitored by a qualified healthcare professional as part of an integrated plan.",
            "how_to_use": "Inject once weekly as directed by a medical provider.\nAdminister into the abdomen, thigh, or upper arm, rotating injection sites to maintain comfort.\nBegin at a lower dose and titrate gradually to minimise digestive and systemic side effects.\nAlign use with protein-focused nutrition, hydration, and resistance training for best outcomes.",
            "customers_know": "Survodutide is intended for use within a medically supervised programme; it is not a casual or stand-alone cosmetic product.\nSuitability depends on individual health status, medical history, and current medications, including other weight-management agents.\nCommon early effects may include nausea, reduced appetite, increased fullness, digestive changes (constipation, diarrhoea, or bloating), reflux, and mild fatigue.\nSmaller meals, moderated dietary fat, and consistent hydration can improve comfort during dose escalation.\nOutcomes are influenced by lifestyle, dose progression, and duration of therapy; it is designed for steady, programme-based change.",
            "faqs": "How long until I see results?\nMany clients notice appetite and satiety changes within the first few weeks. Visible changes in weight, waist circumference, and body composition generally build over several weeks to months when combined with consistent nutrition and training.\n\nWhat are the common side effects?\nCommonly reported effects include nausea, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue, especially during initiation or dose increases. These often settle as the body adapts and doses stabilise.\n\nHow do I store it?\nRefrigerate at 2-8C. Do not freeze. Keep protected from direct sunlight and heat, and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nSurvodutide may be paired with selected peptides and metabolic supports, but combinations must be carefully designed. Stacking should only occur under professional guidance to avoid overlap, excessive appetite suppression, or unnecessary side effects.\n\nIs this suitable for beginners?\nIt can be suitable for appropriately screened beginners who require advanced medical support for fat loss. A thorough assessment, clear expectations, and regular follow-up are essential.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Mazdutide 5mg",
            "benefits": "Dual GLP-1 / glucagon receptor agonist for advanced weight and metabolic management.\nSupports appetite regulation and reduced food cravings.\nHelps improve metabolic efficiency and post-meal glucose handling.\nMay assist with clinically meaningful weight and waist reduction in structured programmes.",
            "usage": "Once-weekly subcutaneous injection, with guided dose titration.",
            "price": 129.00,
            "desc": "Mazdutide is an advanced injectable therapy used in medically supervised weight management and metabolic programmes. It acts on gut-hormone pathways involved in appetite, digestion, and glucose control, helping the body manage food intake and energy balance more effectively.\n\nClients typically consider mazdutide when they are looking for a structured, clinical approach to fat loss that goes beyond lifestyle alone. It is positioned as part of an integrated plan that brings together appetite control, metabolic support, and long-term adherence to nutrition and training.",
            "full_benefits": "Appetite regulation: Helps reduce hunger signals and \"food noise,\" supporting smaller portions and fewer unplanned snacks.\nGlucose support: Encourages a more stable blood sugar response after meals as part of metabolic care.\nFat-loss assistance: May support reductions in body weight, waist circumference, and broader metabolic risk markers over time.\nConvenient dosing schedule: Once-weekly injections favour long-term adherence in busy lifestyles.",
            "dosage": "Typically initiated at a low once-weekly dose to assess tolerance.\nDose increases are made gradually every few weeks based on appetite response, side-effect profile, and overall progress.\nThe maintenance dose is personalised to the individual's goals and clinical picture.\nAll dosing decisions should be made and monitored by a qualified healthcare professional within a supervised programme.",
            "how_to_use": "Inject once weekly exactly as directed by a medical provider.\nAdminister into the abdomen, thigh, or upper arm, rotating injection sites regularly.\nBegin at a lower dose and titrate slowly to minimise digestive and systemic side effects.\nFor best outcomes, pair with protein-focused nutrition, hydration, and resistance training.",
            "customers_know": "Mazdutide is intended for use in medically supervised programmes; it is not a casual or cosmetic stand-alone product.\nSuitability depends on medical history, current medications, and overall metabolic status.\nCommon early effects can include nausea, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue, especially during initiation or dose escalation.\nSmaller meals, moderated dietary fat, and consistent hydration usually improve comfort as the body adapts.\nResults are shaped by lifestyle, dose progression, and duration of therapy; it is designed for gradual, programme-based change rather than short-term quick fixes.",
            "faqs": "How long until I see results?\nMany clients notice changes in appetite and satiety within the first few weeks. Visible shifts in weight, waist circumference, and body composition generally build over several weeks to months when combined with consistent nutrition, sleep, and training.\n\nWhat are the common side effects?\nCommonly reported effects include nausea, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue, particularly when starting or increasing the dose. These often settle as doses stabilise and the body adapts.\n\nHow do I store it?\nRefrigerate at 2-8C. Do not freeze. Keep protected from direct sunlight and heat and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nMazdutide may be combined with selected metabolic and peptide supports, but stacking should only be done under professional guidance to avoid overlap, excessive appetite suppression, or unnecessary side effects.\n\nIs this suitable for beginners?\nIt can be suitable for appropriately screened beginners who require clinical support for weight management. A thorough assessment, clear expectations, and regular follow-up are essential.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Semaglutide + Cagrilintide 5mg + 5mg (CagriSema)",
            "benefits": "Dual-pathway GLP-1 + amylin injectable for intensive appetite and weight management.\nHelps strongly reduce hunger, food noise, and meal volume to sustain a calorie deficit.\nMay support substantial weight and fat reduction, with broader metabolic improvements in structured programmes.",
            "usage": "Once-weekly subcutaneous injection, with guided dose titration.",
            "price": 279.00,
            "desc": "CagriSema combines a GLP-1 analogue (semaglutide) with a long-acting amylin analogue (cagrilintide) in a single, once-weekly injectable. Together, they act on complementary appetite and satiety pathways, digestion, and glucose control, providing an intensive, dual-axis approach to weight management.\n\nThis combination is often chosen by clients who have high \"food noise\", strong cravings, or who require more robust support than single-pathway therapies alone. It is positioned for structured, medically supervised programmes where body recomposition, metabolic health and long-term adherence are central goals.",
            "full_benefits": "Dual appetite control: GLP-1 and amylin pathways work together to reduce hunger, improve satiety, and lower meal volume.\nMetabolic support: Helps the body handle post-meal glucose more effectively as part of cardiometabolic care.\nIntensive fat-loss assistance: May support substantial reductions in body weight, waist circumference, and visceral fat over time.\nOnce-weekly convenience: A single weekly injection simplifies adherence in complex programmes.",
            "dosage": "Typically initiated at a low once-weekly dose to assess tolerance, with both components titrated carefully.\nDose increases are made gradually every few weeks based on appetite response, side-effect profile, and overall progress.\nThe maintenance dose is individualised and determined within a medically supervised plan.\nAll dosing decisions for the combination should be made and monitored by a qualified healthcare professional.",
            "how_to_use": "Inject once weekly exactly as directed by a medical provider.\nAdminister into the abdomen, thigh, or upper arm, rotating injection sites regularly.\nStart at a lower dose and titrate slowly to minimise digestive and systemic side effects.\nPair with protein-focused nutrition, hydration, and resistance training to optimise outcomes.",
            "customers_know": "This is an advanced, prescription-only combination and should only be used within a medically supervised programme.\nSuitability depends on individual medical history, current medications, and prior response to GLP-1 or amylin-axis therapies.\nCommon early effects can include nausea, increased fullness, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue.\nSmaller, lower-fat meals and consistent hydration can improve comfort, especially during dose escalation.\nResults are influenced by lifestyle, dose progression, and duration of therapy; it is intended for steady, programme-based change rather than short-term use.",
            "faqs": "How long until I see results?\nMany clients notice pronounced changes in appetite and satiety within the first few weeks. Visible changes in weight and waist circumference typically build over several weeks to months, especially when combined with consistent nutrition, sleep, and training.\n\nWhat are the common side effects?\nCommonly reported effects include increased fullness, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue, particularly during initiation or up-titration. These often lessen as doses stabilise and the body adapts.\n\nHow do I store it?\nRefrigerate at 2-8C. Do not freeze. Keep protected from direct sunlight and heat, and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nBecause CagriSema already combines two potent pathways, any additional stacking must be selected with great care. Additional peptides or agents should only be introduced under expert guidance to avoid excessive appetite suppression or overlapping side effects.\n\nIs this suitable for beginners?\nIt may be suitable for carefully screened beginners who require intensive, clinically guided weight management. A thorough assessment, clear expectations, and regular monitoring are essential.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Retatrutide + Cagrilintide 5mg + 5mg",
            "benefits": "Multi-receptor + amylin dual-pathway injectable for intensive appetite and fat-loss programmes.\nHelps strongly reduce hunger, food noise, and meal volume to support a sustained calorie deficit.\nMay assist with substantial weight, fat, and waist reduction alongside broader metabolic improvements.",
            "usage": "Once-weekly subcutaneous injection, with guided dose titration.",
            "price": 299.00,
            "desc": "This combination pairs a multi-receptor metabolic injectable (retatrutide-class) with a long-acting amylin analogue (cagrilintide) in a single, once-weekly protocol. Together, they act on complementary appetite, satiety, digestion, and energy-balance pathways, creating a highly intensive, dual-axis approach to weight management.\n\nIt is typically reserved for clients who require a more powerful, clinically guided strategy - those with pronounced \"food noise\", strong cravings, or who have only partially responded to single-pathway therapies. The focus is on structured body recomposition, metabolic health and adherence, under close professional supervision.",
            "full_benefits": "Dual appetite and satiety control: Multi-receptor signalling plus amylin-axis support to reduce hunger, increase fullness, and reduce meal volume.\nMetabolic and energy support: Designed to assist glucose handling and overall energy balance as part of a comprehensive programme.\nIntensive fat-loss assistance: May support marked reductions in body weight, central fat, and waist circumference over time.\nOnce-weekly convenience: A single weekly protocol helps simplify adherence in complex treatment plans.",
            "dosage": "Generally initiated at a low once-weekly dose to assess tolerance to both components.\nDose increases are introduced gradually every few weeks based on appetite response, body-composition changes, and side-effect profile.\nThe maintenance dose is individualised and determined within a medically supervised framework.\nAll dosing decisions for the combination must be made and monitored by a qualified healthcare professional.",
            "how_to_use": "Inject once weekly exactly as directed by a medical provider.\nAdminister into the abdomen, thigh, or upper arm, rotating injection sites to protect skin integrity.\nBegin at a lower dose and titrate slowly to minimise digestive and systemic side effects.\nFor best results, combine with protein-focused nutrition, hydration, resistance training, and adequate sleep.",
            "customers_know": "This is an advanced, prescription-only combination intended strictly for medically supervised programmes.\nSuitability depends on individual medical history, current medications, prior response to similar agents, and overall metabolic status.\nCommon early effects may include nausea, pronounced fullness, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue.\nSmaller meals, moderate dietary fat, and consistent hydration generally improve comfort during dose escalation.\nOutcomes are shaped by lifestyle, dose progression, and duration of therapy; this protocol is designed for sustained, programme-based change rather than short-term or casual use.",
            "faqs": "How long until I see results?\nMany clients notice strong appetite and satiety changes within the first few weeks. Visible changes in weight, waist circumference, and body composition usually build progressively over several weeks to months when supported by consistent nutrition and training.\n\nWhat are the common side effects?\nFrequently reported effects include increased fullness, reduced appetite, constipation or diarrhoea, reflux or burping, bloating, and mild fatigue - especially when starting or increasing the dose. These often ease as doses stabilise and the body adapts.\n\nHow do I store it?\nRefrigerate at 2-8C. Keep protected from direct sunlight and heat and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nBecause this combination is already highly potent, any additional stacking must be approached with caution. Extra peptides or agents should only be added under expert guidance to avoid over-suppression of appetite, overlapping mechanisms, or unnecessary side effects.\n\nIs this suitable for beginners?\nIt may be suitable for carefully screened beginners with significant metabolic or weight-management needs, but only within a closely supervised clinical programme. A thorough assessment, clear goals, and regular monitoring are essential.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "AOD9604 5mg",
            "benefits": "Fragmented growth-hormone peptide designed to support targeted fat-loss protocols.\nMay assist with mobilisation of stored fat when combined with a structured plan.\nComplements appetite-based therapies by focusing on body-composition and stubborn areas.",
            "usage": "Once-daily subcutaneous injection, typically used in cycles as part of a supervised programme.",
            "price": 99.00,
            "desc": "AOD9604 is a peptide fragment originally derived from the human growth-hormone (HGH) molecule, designed to focus on fat-metabolism pathways without the broad anabolic effects associated with full-length GH. It is used in medically guided programmes as a support agent for fat loss and body-composition work.\n\nRather than acting on appetite or blood sugar directly, AOD9604 is positioned as a complementary tool alongside diet, training, and primary metabolic therapies. It is often used by clients seeking an additional nudge on stubborn fat areas, or as part of a structured recomposition or aesthetics-focused protocol.",
            "full_benefits": "Targeted fat-loss support: Designed to support fat breakdown and utilisation when paired with an appropriate calorie deficit and activity plan.\nNon-anabolic profile: Developed to avoid traditional growth-hormone effects on IGF-1 and tissue overgrowth, making it more focused on fat metabolism.\nStack-friendly: Complements GLP-1 / GIP / amylin-axis therapies by addressing body-composition and stubborn areas rather than appetite alone.\nFlexible use: Can be incorporated into both cutting phases and aesthetic refinement blocks under professional guidance.",
            "dosage": "Commonly used as a once-daily subcutaneous injection at a low to moderate dose, as directed by a clinician.\nOften run in blocks (for example, 8-12 weeks) within a larger programme.\nDosage, timing, and cycle length should be tailored to individual goals, tolerance, and the broader protocol.\nAll dosing decisions should be made and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject subcutaneously once daily, ideally at a consistent time, as directed by your provider.\nUsual injection sites include the abdomen, thigh, or upper buttock; rotate sites regularly.\nBest used as part of a clearly defined nutrition, training, and peptide plan rather than in isolation.\nWorks particularly well when combined with adequate protein intake, resistance training, and overall calorie control.",
            "customers_know": "AOD9604 is a support peptide used within structured programmes, not a stand-alone solution or replacement for lifestyle changes.\nSuitability depends on individual health status, goals, and any concurrent therapies.\nSide-effects are generally mild when used appropriately, but can include local injection-site irritation or transient discomfort in some individuals.\nExpectations should be aligned with its role as an adjunct: it is designed to complement, not replace, core fat-loss strategies such as nutrition, movement, and primary metabolic agents.",
            "faqs": "How long until I see results?\nMost clients use AOD9604 over several weeks as part of a broader plan. Changes are usually subtle and best appreciated in combination with consistent nutrition, training, and, where appropriate, other metabolic therapies.\n\nWhat are the common side effects?\nIt is generally well tolerated when used as directed. Some individuals may notice mild redness, itching, or tenderness at the injection site. Any unusual or persistent symptoms should be discussed with a healthcare professional.\n\nHow do I store it?\nStore refrigerated at 2-8C. Do not freeze. Keep protected from direct sunlight and heat, and avoid temperature extremes.\n\nCan I stack this with other fat-loss supports?\nYes, AOD9604 is commonly used as a stack component with GLP-1 / GIP / amylin-axis therapies, carnitine, NAD+ and training-focused protocols. Stacks should always be planned and monitored by a professional to ensure coherence and safety.\n\nIs this suitable for beginners?\nIt can be considered for beginners who are already committed to lifestyle changes and are part of a supervised programme. It is most effective when the fundamentals - nutrition, activity, and sleep - are in place.",
            "storage": "Store refrigerated at 2-8C. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "5-Amino-1MQ 10mg",
            "benefits": "Metabolic support compound used alongside peptide-based fat-loss protocols.\nMay assist with improving cellular energy balance and fat utilisation when lifestyle is optimised.\nComplements GLP-1 and fat-loss peptides by targeting a different metabolic pathway.",
            "usage": "Once-daily subcutaneous injection, typically in defined cycles under supervision.",
            "price": 109.00,
            "desc": "5-Amino-1MQ is a small-molecule metabolic support compound commonly included in advanced body-composition and fat-loss programmes. It is designed to act on cellular pathways involved in energy balance and fat storage, making it a useful adjunct for clients who are already serious about nutrition, training, and structured protocols.\n\nWithin a VANTIS programme, 5-Amino-1MQ is positioned as a background metabolic amplifier, not a front-line appetite drug. It fits best in clients who are already using core injectables (such as GLP-1 or dual agonists), and who want an additional layer of mechanistic support for fat-loss and recomposition.",
            "full_benefits": "Metabolic pathway support: Targets cellular signalling linked to fat storage and energy use, helping fat-loss efforts when diet and training are in place.\nStack-friendly design: Works alongside GLP-1, amylin-axis and other peptide therapies by supporting underlying metabolic efficiency rather than appetite alone.\nNon-hormonal mechanism: Does not mimic gut hormones or growth hormone, providing a distinct tool in multi-layered protocols.\nBody-composition focused: Best suited for structured fat-loss and recomposition phases rather than casual or short-term use.",
            "dosage": "Commonly used as a low-dose, once-daily subcutaneous injection (for example, 10mg per day), as directed by a clinician.\nOften run in cycles, such as 6-12 weeks, as part of a broader protocol.\nDose, timing, and cycle length should be individualised based on goals, tolerance, and the surrounding stack.\nAll dosing decisions should be made and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject subcutaneously once daily at a consistent time, as advised by your provider.\nTypical injection sites include the lower abdomen, outer thigh, or upper buttock; rotate sites to maintain skin comfort.\nIntegrate only into a clearly defined plan that already includes structured nutrition, resistance training, and recovery.\nWorks best when paired with adequate protein intake, stable blood sugar control, and regular physical activity.",
            "customers_know": "5-Amino-1MQ is a support compound, designed to enhance a complete programme - not a stand-alone fat-loss solution.\nSuitability depends on medical history, other medications, and the overall design of the protocol.\nSide-effects are usually mild, but may include local injection-site irritation, digestive discomfort, headache, or temporary shifts in energy.\nRealistic expectations are important: its role is to complement a well-built plan, not to replace the fundamentals.",
            "faqs": "How long until I see results?\nMost clients use 5-Amino-1MQ over several weeks as part of a stack. Changes tend to be subtle and are best tracked via body-composition, performance, and overall energy rather than scale weight alone.\n\nWhat are the common side effects?\nIt is generally well tolerated when used as directed. Some individuals may notice mild digestive upset, headache, or local injection-site irritation. Any persistent or concerning symptoms should be reviewed with a healthcare professional.\n\nHow do I store it?\nStore refrigerated at 2-8C after reconstitution. Do not freeze. Keep protected from direct sunlight and heat and follow any specific storage instructions supplied with the vial.\n\nCan I stack this with other fat-loss supports?\nYes. It is commonly positioned as a stack component with GLP-1 / GIP / amylin-axis injectables, L-Carnitine, NAD+ support, and performance-focused protocols. Stacks should always be professionally designed to ensure synergy and avoid redundancy.\n\nIs this suitable for beginners?\nIt may be appropriate for beginners who are already committed to a structured, supervised programme. It is not intended as a shortcut for those who have not yet addressed nutrition, movement, and sleep.",
            "storage": "Store refrigerated at 2-8C after reconstitution. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "MOTS-C 10mg",
            "benefits": "Mitochondrial peptide designed to support cellular energy and metabolic resilience.\nMay assist with improved exercise tolerance, recovery, and body-composition work.\nComplements fat-loss and performance protocols by working at the cellular level.",
            "usage": "Subcutaneous injection, typically 3-5 times per week in defined cycles.",
            "price": 149.00,
            "desc": "MOTS-c is a mitochondrial-derived peptide used in advanced programmes to support cellular energy production, metabolic flexibility, and training capacity. It is designed to work at the level of the mitochondria, where the body generates energy, making it a valuable tool for clients focused on performance, body composition, and healthy ageing.\n\nWithin a VANTIS protocol, MOTS-c is positioned as a foundational metabolic and performance support peptide. Rather than suppressing appetite, it is used to help the body handle energy demands more efficiently - especially in clients who are training regularly, working through fat-loss phases, or rebuilding after periods of metabolic stress.",
            "full_benefits": "Cellular energy support: Helps support mitochondrial function, which may improve how the body produces and uses energy.\nMetabolic resilience: Often used to support metabolic flexibility, exercise tolerance, and recovery in structured programmes.\nPerformance and composition: Especially valued by active clients who want to maintain or improve training quality while pursuing fat-loss or recomposition goals.\nStack-friendly: Integrates well with GLP-1, carnitine, NAD+ and other support peptides without overlapping appetite pathways.",
            "dosage": "Commonly used as a subcutaneous injection 3-5 times per week at a clinician-directed dose (for example, on training days or across the week).\nOften run in 4-8 week cycles, with rest periods as advised by the overseeing practitioner.\nDose, frequency, and cycle length should be tailored to the individual's goals, training load, and wider protocol.\nAll dosing decisions should be made and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject subcutaneously into the lower abdomen, outer thigh, or upper buttock, rotating sites to maintain skin comfort.\nCan be timed around training days or spread across the week, according to program design.\nWorks best when combined with structured training, appropriate nutrition (including adequate protein), and recovery practices.\nShould be integrated thoughtfully into multi-peptide or multi-agent stacks to maintain clarity of effect.",
            "customers_know": "MOTS-c is a support peptide designed for structured programmes, not a stand-alone fat-loss solution.\nIt is particularly suited to clients who train regularly or are rebuilding metabolic health and exercise capacity.\nSide-effects are typically mild but may include local injection-site irritation or transient changes in energy or sleep in some individuals.\nAs with any advanced protocol, realistic expectations and consistent lifestyle habits are key to seeing benefit.",
            "faqs": "How long until I see results?\nMost clients use MOTS-c over several weeks. Changes are often noticed as improved training tolerance, steadier energy, or better recovery, rather than a dramatic change on the scale. It works best when tracked alongside training logs, performance, and body-composition data.\n\nWhat are the common side effects?\nIt is generally well tolerated when used as directed. Some individuals may experience mild redness, itching, or tenderness at the injection site, or temporary changes in energy or sleep patterns. Any persistent or concerning symptoms should be reviewed with a healthcare professional.\n\nHow do I store it?\nStore refrigerated at 2-8C after reconstitution. Do not freeze. Keep protected from direct sunlight and heat, and follow any specific storage instructions supplied with the vial.\n\nCan I stack this with other fat-loss supports?\nYes. MOTS-c is commonly combined with GLP-1 / GIP / amylin injectables, AOD9604, L-Carnitine, NAD+ and performance-focused protocols. Stacks should always be designed professionally to ensure synergy and avoid unnecessary overlap.\n\nIs this suitable for beginners?\nIt can be suitable for beginners who are already committed to a structured programme and are engaging in regular training. It is especially relevant for those focused on performance, recovery, and metabolic resilience, rather than quick-fix weight loss.",
            "storage": "Store refrigerated at 2-8C after reconstitution. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Tesamorelin 10mg",
            "benefits": "Growth-hormone-releasing peptide focused on visceral fat and metabolic repair.\nMay help reduce deep abdominal fat and support lean body mass.\nComplements fat-loss and longevity programmes by targeting hormonal and cellular regeneration.",
            "usage": "Subcutaneous injection, typically once daily, usually in the evening on an empty stomach.",
            "price": 139.00,
            "desc": "Tesamorelin is a synthetic growth-hormone-releasing hormone (GHRH) analogue used in medically supervised programmes to stimulate the body's own production of growth hormone in a more physiologic way. It is best known for its role in reducing visceral abdominal fat and supporting metabolic health, while also influencing tissue repair and body composition.\n\nWithin a VANTIS protocol, Tesamorelin is positioned as a metabolic rejuvenation and body-composition peptide, particularly suited to clients with central fat accumulation, age-related metabolic slowdown, or recovery and regeneration goals. It works upstream of traditional GH, encouraging controlled, pulsatile release rather than blunt exogenous replacement.",
            "full_benefits": "Visceral fat support: Used to target deep abdominal (visceral) fat, which is closely linked to cardiometabolic risk and central obesity.\nBody-composition and lean mass: By supporting endogenous growth hormone release, it may help preserve or improve lean mass when paired with resistance training and adequate protein.\nMetabolic and recovery support: Often used to support lipid profiles, sleep quality, tissue repair, and overall recovery capacity in structured programmes.\nLongevity-aligned mechanism: Acts through the body's own GH axis, aiming for a more physiological pattern of hormone release rather than supraphysiologic GH exposure.",
            "dosage": "Commonly used as a once-daily subcutaneous injection at a clinician-directed dose (for example, in the range of 1-2 mg daily, titrated to response and tolerance; reconstituted from the 10mg vial).\nTypically administered in the evening, at least 2 hours after the last meal, to align with natural GH rhythms.\nOften run in cycles of several months, with periodic reassessment of body composition, metabolic markers, and overall response.\nAll dosing decisions should be made and monitored by a qualified healthcare professional, with appropriate screening and follow-up.",
            "how_to_use": "Inject subcutaneously once daily into the lower abdomen, outer thigh, or upper buttock, rotating sites to maintain skin comfort.\nUse on an empty stomach (for example, before bed, several hours after the last meal) unless advised otherwise.\nFor best results, integrate with a structured nutrition plan, higher protein intake, resistance training, and sleep optimisation.\nConsistency of timing and adherence to the dosing schedule are important for stable results.",
            "customers_know": "Tesamorelin is a prescription peptide and should only be used within a medically supervised programme.\nIt is particularly relevant for clients with central fat accumulation and age-related metabolic decline, not as a casual or short-term cosmetic tool.\nPossible side effects can include injection-site reactions, fluid shifts (such as mild swelling), joint or muscle aches, changes in glucose handling, or sleep changes in some individuals.\nBaseline and follow-up assessments - such as body composition, waist measurements, metabolic markers, and symptom tracking - are important to evaluate progress and safety.\nIt works best as part of a complete plan that includes nutrition, training, and recovery, rather than used in isolation.",
            "faqs": "How long until I see results?\nChanges in sleep quality, recovery and general wellbeing may be noticed within several weeks. Visible changes in central fat and body composition typically build progressively over a few months, especially when combined with nutrition and training.\n\nWhat are the common side effects?\nCommonly reported effects can include redness or irritation at the injection site, mild fluid retention, joint or muscle discomfort, tingling sensations, or changes in sleep or glucose handling. Any persistent or concerning symptoms should be reviewed with a healthcare professional.\n\nHow do I store it?\nStore refrigerated at 2-8C after reconstitution. Do not freeze. Keep protected from direct sunlight and heat. Follow any additional storage instructions supplied with the vial.\n\nCan I stack this with other fat-loss supports?\nYes. Tesamorelin is often combined with GLP-1 / GIP / amylin-axis injectables, AOD9604, MOTS-c, carnitine, and NAD+ as part of a multi-layered metabolic and aesthetics programme. Stacks must be designed and monitored professionally to maintain safety and clear objectives.\n\nIs this suitable for beginners?\nIt may be suitable for carefully screened beginners, particularly those with central adiposity and metabolic risk factors, but it is still an advanced peptide. A thorough assessment, clear expectations, and structured follow-up are essential before starting.",
            "storage": "Store refrigerated at 2-8C after reconstitution. Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "L-Carnitine 600mg",
            "benefits": "Supports transport of fatty acids into mitochondria for energy production.\nMay assist with training performance, endurance, and recovery.\nComplements fat-loss and performance stacks by enhancing fat utilisation during activity.",
            "usage": "Intramuscular or slow subcutaneous injection, typically several times per week as guided.",
            "price": 59.00,
            "desc": "L-Carnitine is a naturally occurring compound involved in transporting long-chain fatty acids into the mitochondria, where they can be used for energy. In a clinical or performance context, injectable L-Carnitine is used to support fat utilisation, training output, and recovery, especially in individuals with high activity demands or structured fat-loss goals.\n\nWithin a VANTIS protocol, L-Carnitine is positioned as a performance-oriented metabolic support agent. It does not suppress appetite or act like GLP-1 therapies; instead, it is used to make better use of fats as a fuel source during training and to support overall energy metabolism in active clients.",
            "full_benefits": "Fat transport and utilisation: Supports the movement of fatty acids into mitochondria to be used as fuel during activity.\nTraining and endurance: Often used to help maintain performance, reduce perceived fatigue, and support longer or more frequent training sessions.\nRecovery and body composition: May assist with recovery and body-composition work when combined with proper nutrition and a structured training programme.\nStack-friendly: Pairs well with GLP-1, MOTS-c, 5-Amino-1MQ and NAD+ as part of a comprehensive metabolic and performance stack.",
            "dosage": "Commonly administered several times per week at a clinician-directed dose (for example, 600-1200mg on training or key programme days).\nRoute (intramuscular vs slow subcutaneous), frequency, and timing are tailored to individual goals and tolerance.\nOften used in 4-8 week blocks within fat-loss, recomposition, or performance phases.\nAll dosing decisions should be made and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject intramuscularly (for example, into the deltoid, glute, or thigh) or as a slow subcutaneous injection, according to medical guidance.\nCan be timed around training sessions (such as pre-workout days) or distributed across the week, depending on programme design.\nWorks best when integrated with a structured training plan, appropriate caloric intake, and adequate hydration.\nShould be part of a clearly defined protocol rather than used sporadically.",
            "customers_know": "L-Carnitine is a support product, ideal for active clients and structured programmes - on its own it will not drive fat loss without nutrition and training changes.\nSuitability depends on medical history, overall protocol design, and current medications.\nPossible side effects can include mild injection-site discomfort, digestive upset, or a transient \"fishy\" body odour in some individuals.\nIt is most effective when used consistently and tracked via training performance, recovery, and body-composition trends rather than scale weight alone.",
            "faqs": "How long until I see results?\nMost clients use L-Carnitine over several weeks. Benefits are usually noticed as improved training tolerance, steadier energy, or better recovery, rather than dramatic changes on the scale. It works synergistically with diet, training, and other metabolic supports.\n\nWhat are the common side effects?\nIt is generally well tolerated when used as directed. Some individuals may experience local injection-site soreness, mild digestive discomfort, or a temporary change in body odour. Any persistent or concerning symptoms should be reviewed with a healthcare professional.\n\nHow do I store it?\nStore in a cool place, ideally between 2-8C if recommended by the manufacturer. Do not freeze. Protect from direct sunlight and heat, and keep vials sealed until use.\n\nCan I stack this with other fat-loss supports?\nYes. L-Carnitine is frequently used alongside GLP-1 / GIP / amylin injectables, AOD9604, MOTS-c, 5-Amino-1MQ and NAD+ as part of performance- and fat-loss-focused stacks. Stacking should always be guided professionally.\n\nIs this suitable for beginners?\nIt can be suitable for beginners who are already training regularly and following a structured plan. It is particularly relevant for those who value performance and recovery as much as body-composition changes.",
            "storage": "Store as directed (commonly in a cool environment, often 2-8C). Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "LIPO-C 120mg",
            "benefits": "Injectable lipotropic blend designed to support liver function and fat-metabolism pathways.\nMay assist with energy, fat utilisation, and reduction of \"sluggish\" dieting phases.\nComplements GLP-1 and peptide stacks by supporting detoxification and metabolic efficiency.",
            "usage": "Intramuscular or slow subcutaneous injection, typically 1-3 times per week under supervision.",
            "price": 89.00,
            "desc": "LIPO-C is an injectable lipotropic formulation typically containing a combination of nutrients such as Methionine, Inositol, Choline, and supportive cofactors (often paired with vitamins like B12, depending on the specific compound). It is designed to support liver function, fat transport, and overall metabolic efficiency, especially during structured fat-loss or recomposition phases.\n\nIn a VANTIS protocol, LIPO-C is positioned as a supportive \"metabolic hygiene\" and liver-focused product, helping to optimise how the body handles fats and processes by-products of intensive fat-loss and pharmacological protocols. It is not an appetite suppressant, but a background support tool within a larger strategy.",
            "full_benefits": "Liver and fat-processing support: Helps support the liver's role in processing fats and metabolic by-products during fat-loss programmes.\nFat transport and utilisation: Lipotropic components assist with the mobilisation and transport of fatty acids as part of an overall diet and training plan.\nEnergy and wellbeing: Many clients report steadier energy and less \"sluggishness\" when LIPO-C is used during cutting or high-demand phases.\nStack-friendly support: Integrates smoothly with GLP-1, peptides, and metabolic stacks by focusing on liver and nutrient pathways rather than hormone axes.",
            "dosage": "Commonly administered 1-3 times per week at a clinician-directed dose (for example, 1ml per injection, depending on concentration).\nRoute (intramuscular vs slow subcutaneous), frequency, and cycle length are tailored to the individual and overall programme.\nOften used in parallel with active fat-loss blocks, detoxification or recomposition phases.\nAll dosing decisions should be made and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject intramuscularly (e.g., deltoid, glute, or thigh) or as a slow subcutaneous injection as advised by your provider.\nCan be scheduled on training days, check-in days, or at evenly spaced intervals through the week.\nWorks best as part of a comprehensive plan that includes hydration, appropriate nutrition, and regular movement.\nShould be integrated thoughtfully with other injectables to avoid unnecessary needle burden.",
            "customers_know": "LIPO-C is a support formulation - its role is to assist liver and fat-processing pathways, not to replace nutrition, training, or primary fat-loss agents.\nSuitability depends on medical history, liver health, and the rest of the protocol.\nSide-effects are generally mild, but may include injection-site discomfort, flushing, or mild digestive changes in some individuals.\nIt is most effective when used consistently and tracked via energy, recovery, and body-composition trends rather than scale weight alone.",
            "faqs": "How long until I see results?\nMost clients use LIPO-C throughout a fat-loss or recomposition phase. Benefits are often experienced as improved energy, less heaviness, and better tolerance of dietary changes, rather than a dramatic direct drop on the scale.\n\nWhat are the common side effects?\nCommonly mild and can include local injection-site soreness, a brief warmth or flushing sensation, or mild digestive changes. Any persistent or concerning symptoms should be reviewed with a healthcare professional.\n\nHow do I store it?\nStore according to the manufacturer's recommendations, typically in a cool place, often between 2-8C. Do not freeze. Protect from direct sunlight and heat.\n\nCan I stack this with other fat-loss supports?\nYes. LIPO-C is frequently combined with GLP-1 / GIP / amylin injectables, AOD9604, MOTS-c, 5-Amino-1MQ, L-Carnitine and NAD+ as liver and metabolic support in more complex stacks. Stacking should always be planned under professional guidance.\n\nIs this suitable for beginners?\nIt can be suitable for beginners who are in a structured programme and want additional liver and metabolic support during fat-loss phases. It should not be used as a substitute for diet, movement, or primary therapies.",
            "storage": "Store as directed (commonly in a cool environment, often 2-8C). Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "LIPO-C 216mg",
            "benefits": "Higher-strength lipotropic blend for intensive liver and fat-metabolism support.\nMay assist with energy, fat utilisation, and tolerance of more aggressive fat-loss phases.\nComplements GLP-1 and peptide stacks by supporting detoxification and metabolic efficiency at a higher dose.",
            "usage": "Intramuscular or slow subcutaneous injection, typically 1-2 times per week under supervision.",
            "price": 99.00,
            "desc": "LIPO-C 216mg is a higher-potency lipotropic formulation designed for structured fat-loss and recomposition programmes. It typically contains a concentrated combination of Methionine, Inositol, Choline, and supportive cofactors (often with B-vitamins), with the aim of supporting liver function, fat transport, and overall metabolic efficiency during more demanding phases.\n\nWithin a VANTIS protocol, LIPO-C 216mg is positioned as an \"intensive phase\" liver and metabolic support product, suited to clients running higher-load fat-loss or peptide stacks. It focuses on how the body processes fats and metabolic by-products, rather than appetite suppression.",
            "full_benefits": "Enhanced liver support: Higher-strength formulation to support the liver while it processes fats and by-products of intensive fat-loss protocols.\nFat transport and utilisation: Lipotropic ingredients assist with mobilising and transporting fatty acids as part of a structured nutrition and training plan.\nEnergy and clarity: Many clients report steadier energy and less feeling of heaviness or \"sluggishness\" during more aggressive cutting blocks.\nStack-oriented role: Designed to sit in the background of GLP-1 and peptide stacks, supporting metabolic hygiene without overlapping hormone pathways.",
            "dosage": "Typically administered 1-2 times per week at a clinician-directed volume (for example, 1ml per injection, adjusted for concentration and individual needs).\nRoute (intramuscular vs slow subcutaneous), frequency, and cycle duration are tailored to the programme intensity and client tolerance.\nCommonly run in parallel with active fat-loss, recomposition, or detoxification-style phases.\nAll dosing should be prescribed and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject intramuscularly (e.g., deltoid, glute, or thigh) or as a slow subcutaneous injection, exactly as advised.\nCan be placed on training days, \"heavier\" dietary days, or evenly spaced during the week, depending on protocol design.\nWorks best with adequate hydration, appropriate nutrition (including sufficient protein and micronutrients), and regular movement.\nShould be integrated into the overall injection schedule to avoid unnecessary frequency or overlap.",
            "customers_know": "LIPO-C 216mg is a support formulation at a higher strength - it helps the system cope with fat-loss demands but does not replace diet, movement, or primary fat-loss medications.\nSuitability depends on individual liver health, medication profile, and the intensity of the overall programme.\nSide-effects are generally mild, but can include injection-site discomfort, brief warmth or flushing, or mild digestive changes in some individuals.\nIt is best evaluated through energy, digestion, recovery, and body-composition changes rather than scale weight alone.",
            "faqs": "How long until I see results?\nMost clients use LIPO-C 216mg across the full length of a fat-loss or recomposition phase. Benefits are often experienced as improved energy, better tolerance to diet and stacks, and less heaviness, rather than as a direct weight-drop agent.\n\nWhat are the common side effects?\nPotential side effects include mild soreness at the injection site, transient flushing, or mild digestive changes. Any persistent or significant symptoms should be reviewed with a healthcare professional.\n\nHow do I store it?\nStore according to the product's instructions, commonly in a cool environment (often 2-8C). Do not freeze. Protect from direct sunlight and heat, and keep vials sealed until use.\n\nCan I stack this with other fat-loss supports?\nYes. LIPO-C 216mg is frequently used as a background liver and metabolic support with GLP-1 / GIP / amylin injectables, AOD9604, MOTS-c, 5-Amino-1MQ, L-Carnitine, and NAD+ as part of more intensive protocols. Stacking should always be professionally designed.\n\nIs this suitable for beginners?\nIt may be suitable for beginners who are engaged in structured programmes and need added support for liver and fat-processing, particularly when other agents are involved. It is not a stand-alone weight-loss solution.",
            "storage": "Store as directed (commonly in a cool environment, often 2-8C). Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "LIPO-C Fat Blaster 526mg",
            "benefits": "Ultra-strength lipotropic blend for high-intensity liver and fat-metabolism support.\nMay assist with fat mobilisation, smoother cutting phases, and steadier energy.\nDesigned to complement advanced GLP-1 and peptide stacks in serious fat-loss programmes.",
            "usage": "Intramuscular or slow subcutaneous injection, typically 1 time per week (or as clinically directed).",
            "price": 119.00,
            "desc": "LIPO-C FAT BLASTER 526mg is a high-potency lipotropic injection, formulated for clients on intensive fat-loss or recomposition protocols. It contains a concentrated blend of lipotropic agents (such as Methionine, Inositol, Choline, and supportive cofactors, often with B-vitamins) at a significantly higher total dose than standard formulations. The goal is to support liver function, fat processing, and metabolic comfort during demanding phases.\n\nWithin a VANTIS programme, this product is positioned as a premium \"fat-loss phase accelerator\" and metabolic hygiene tool for advanced users. It is designed to sit in the background of powerful injectable stacks, helping the system process fats and by-products more effectively while clients work at a higher level of intensity.",
            "full_benefits": "High-intensity liver support: Extra-concentrated formulation to assist the liver in processing fats and stack-related metabolic load during aggressive phases.\nEnhanced fat mobilisation: Lipotropic factors are used to support the mobilisation and transport of fatty acids as part of a structured nutrition and training strategy.\nEnergy and programme comfort: Many clients feel clearer and less \"bogged down\" when running strong fat-loss protocols with additional metabolic and liver support.\nAdvanced stack integration: Specifically suited for combination with GLP-1 / dual-agonist / peptide protocols where metabolic stress is higher.",
            "dosage": "Typically administered as a once-weekly injection at a clinician-directed volume (for example, 1ml, adjusted for concentration and individual needs).\nFrequency may be increased or decreased based on overall protocol intensity and individual tolerance but is generally lower due to the higher strength per dose.\nCommonly used for the duration of high-intensity fat-loss or recomposition blocks, with reassessment at each phase.\nAll dosing and scheduling should be determined and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject intramuscularly (e.g., into the deltoid, glute, or thigh) or as a slow subcutaneous injection, exactly as guided by your provider.\nCan be aligned with key training days, check-ins, or used at a consistent weekly interval.\nWorks best when combined with adequate hydration, a structured nutrition plan, and regular movement.\nShould be integrated into the overall injection schedule to avoid unnecessary frequency or confusion.",
            "customers_know": "LIPO-C FAT BLASTER 526mg is a supporting high-dose lipotropic, not a stand-alone fat-loss drug. It is designed to enhance metabolic comfort and processing in demanding programmes.\nIt is best suited for clients already on structured GLP-1 / peptide or advanced fat-loss protocols, not for casual or unsupervised use.\nSide-effects are usually mild, but may include injection-site tenderness, transient flushing or warmth, or mild digestive changes.\nIts benefits are best assessed through changes in energy, digestion, recovery, and programme tolerance, rather than purely scale weight.",
            "faqs": "How long until I see results?\nMost clients notice the benefits of LIPO-C FAT BLASTER over the course of a full fat-loss block - often as better energy, less heaviness, and smoother adherence to the programme, rather than as a dramatic direct weight-drop agent.\n\nWhat are the common side effects?\nPossible side effects include mild soreness at the injection site, brief warmth or flushing, or mild digestive changes. Any unusual, persistent, or significant symptoms should be discussed with a healthcare professional.\n\nHow do I store it?\nStore according to the product instructions, usually in a cool environment (commonly 2-8C). Do not freeze. Protect from direct sunlight and heat, and keep vials sealed until use.\n\nCan I stack this with other fat-loss supports?\nYes. It is specifically designed to sit behind GLP-1 / GIP / amylin injectables, AOD9604, MOTS-c, 5-Amino-1MQ, L-Carnitine, NAD+ and other advanced agents as metabolic and liver support. Stacking should always be professionally planned.\n\nIs this suitable for beginners?\nThis formulation is best reserved for clients who are already on structured, supervised fat-loss programmes - ideally those using more advanced agents. For beginners, standard-strength options may be more appropriate unless otherwise advised by a clinician.",
            "storage": "Store as directed (commonly in a cool environment, often 2-8C). Do not freeze. Protect from direct sunlight.",
        },
        {
            "name": "Super Shred 553mg",
            "benefits": "High-potency multi-component injection designed for intensive fat-loss phases.\nMay support fat mobilisation, metabolic efficiency, and cleaner energy during cutting blocks.\nBuilt to complement advanced GLP-1 and peptide stacks for serious body-recomposition programmes.",
            "usage": "Intramuscular or slow subcutaneous injection, typically 1 time per week (or as clinically directed).",
            "price": 129.00,
            "desc": "SUPER SHRED 553mg is a premium, high-strength injectable formulation designed for clients in advanced, clinically supervised fat-loss or recomposition phases. It combines a concentrated blend of lipotropic and metabolic cofactors (for example, higher-dose Methionine, Inositol, Choline, B-vitamins, and supportive amino acid or nutrient components) tailored to support fat processing, energy production, and overall metabolic comfort during demanding protocols.\n\nIn the VANTIS ecosystem, SUPER SHRED is positioned as the flagship \"phase-up\" metabolic support shot. It is intended for use alongside powerful GLP-1 / dual-agonist / peptide stacks and structured training, helping the body keep pace with the metabolic demands of intensive fat-loss programming.",
            "full_benefits": "High-level metabolic support: Formulated to assist the liver and metabolic pathways involved in processing fats and stack-related by-products during more aggressive phases.\nFat mobilisation and utilisation: Lipotropic and cofactor components are selected to support the mobilisation, transport, and utilisation of fatty acids when paired with proper nutrition and training.\nEnergy, clarity, and adherence: Many clients feel less \"flat\" or sluggish when running stronger protocols with dedicated metabolic support in the background.\nDesigned for advanced stacks: Built to sit alongside GLP-1, dual agonists, AOD9604, MOTS-c, L-Carnitine and other agents in serious programmes.",
            "dosage": "Typically administered as a once-weekly injection at a clinician-directed volume (for example, 1ml per week, adjusted for concentration and individual needs).\nFrequency may be modified (e.g., every 5-10 days) based on the intensity of the overall protocol and client tolerance.\nCommonly used for the full duration of a defined cutting or recomposition block, with reassessment between phases.\nAll dosing decisions should be made and supervised by a qualified healthcare professional.",
            "how_to_use": "Inject intramuscularly (e.g., deltoid, glute, or thigh) or as a slow subcutaneous injection, exactly as recommended by your provider.\nCan be aligned with key training days, check-in days, or kept to a fixed weekly schedule.\nWorks best when combined with adequate hydration, structured nutrition, and regular training.\nShould be thoughtfully integrated into the injection schedule to avoid overload or confusion with other products.",
            "customers_know": "SUPER SHRED 553mg is a supporting high-potency metabolic blend, not a primary fat-loss drug or substitute for GLP-1s, nutrition, or training.\nIt is specifically designed for advanced users on well-structured programmes; it is not intended for casual, unsupervised use.\nSide-effects are usually mild, but can include injection-site tenderness, transient flushing, a sense of warmth, or mild digestive changes in some individuals.\nIts value is best judged by how you feel and perform in the programme - energy, digestion, recovery, and adherence - rather than by scale weight alone.",
            "faqs": "How long until I see results?\nSUPER SHRED is typically used throughout a full fat-loss or recomposition phase. Benefits are often experienced as smoother energy, improved tolerance to diet and stacks, and a \"cleaner\" fat-loss experience, rather than as a direct fat-burn injection on its own.\n\nWhat are the common side effects?\nPotential side effects include mild soreness at the injection site, brief flushing or warmth, or mild digestive changes. Any persistent, unusual, or significant symptoms should be reviewed with a healthcare professional.\n\nHow do I store it?\nStore as directed, commonly in a cool environment (often 2-8C). Do not freeze. Protect from direct sunlight and heat. Keep vials sealed until use and respect expiry dates.\n\nCan I stack this with other fat-loss supports?\nYes. SUPER SHRED is designed to sit behind GLP-1 / GIP / amylin injectables, AOD9604, MOTS-c, 5-Amino-1MQ, L-Carnitine, NAD+ and similar agents as a metabolic and liver-support tool. All stacks should be professionally planned and monitored.\n\nIs this suitable for beginners?\nSUPER SHRED 553mg is best reserved for clients already in structured, supervised programmes - especially those running more advanced pharmacological protocols. For new or lower-intensity programmes, standard lipotropic options may be more appropriate unless otherwise advised.",
            "storage": "Store as directed (commonly in a cool environment, often 2-8C). Do not freeze. Protect from direct sunlight.",
        },
    ]

    for p in products:
        full_info = f"Description\n{p['desc']}\n\nKey Benefits\n{p['full_benefits']}\n\nRecommended Dosage\n{p['dosage']}\n\nHow To Use\n{p['how_to_use']}\n\nWhat Customers Should Know\n{p['customers_know']}\n\nCustomer FAQs\n{p['faqs']}\n\nStorage\n{p['storage']}"
        await db.execute(
            "INSERT INTO products (category_id, name, description, benefits, usage_info, full_info, price, image_url) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (1, p["name"], p["desc"], p["benefits"], p["usage"], full_info, p["price"], "")
        )

    package_data = [
        (1, [("1 Bottle", 179.00), ("5 Bottles", 830.00), ("10 Bottles", 1540.00)]),
        (2, [("1 Bottle", 180.00), ("5 Bottles", 840.00), ("10 Bottles", 1540.00)]),
        (3, [("1 Bottle", 179.00), ("5 Bottles", 830.00), ("10 Bottles", 1540.00)]),
        (4, [("1 Bottle", 119.00), ("5 Bottles", 550.00), ("10 Bottles", 1020.00)]),
        (5, [("1 Bottle", 139.00), ("5 Bottles", 650.00), ("10 Bottles", 1200.00)]),
        (6, [("1 Bottle", 129.00), ("5 Bottles", 600.00), ("10 Bottles", 1110.00)]),
        (7, [("1 Bottle", 279.00), ("5 Bottles", 1300.00), ("10 Bottles", 2390.00)]),
        (8, [("1 Bottle", 299.00), ("5 Bottles", 1390.00), ("10 Bottles", 2560.00)]),
        (9, [("1 Bottle", 99.00), ("5 Bottles", 460.00), ("10 Bottles", 850.00)]),
        (10, [("1 Bottle", 109.00), ("5 Bottles", 510.00), ("10 Bottles", 940.00)]),
        (11, [("1 Bottle", 149.00), ("5 Bottles", 690.00), ("10 Bottles", 1270.00)]),
        (12, [("1 Bottle", 139.00), ("5 Bottles", 650.00), ("10 Bottles", 1200.00)]),
        (13, [("1 Bottle", 59.00), ("5 Bottles", 270.00), ("10 Bottles", 500.00)]),
        (14, [("1 Bottle", 89.00), ("5 Bottles", 410.00), ("10 Bottles", 760.00)]),
        (15, [("1 Bottle", 99.00), ("5 Bottles", 460.00), ("10 Bottles", 850.00)]),
        (16, [("1 Bottle", 119.00), ("5 Bottles", 550.00), ("10 Bottles", 1020.00)]),
        (17, [("1 Bottle", 129.00), ("5 Bottles", 600.00), ("10 Bottles", 1110.00)]),
    ]

    for prod_id, options in package_data:
        for opt_name, opt_price in options:
            await db.execute(
                "INSERT INTO package_options (product_id, name, price) VALUES (?, ?, ?)",
                (prod_id, opt_name, opt_price)
            )

    await db.executemany("INSERT INTO faqs (question, answer, sort_order) VALUES (?, ?, ?)", [
        ("What payment methods do you accept?", "We accept PayNow (Singapore) and credit/debit cards via Stripe.", 1),
        ("How long does delivery take?", "Standard delivery takes 3-5 business days. Express delivery takes 1-2 business days.", 2),
        ("Can I return a product?", "Yes, we accept returns within 14 days of delivery if the product is unopened and in original packaging.", 3),
        ("Do you ship internationally?", "Currently we only ship within Singapore. International shipping coming soon.", 4),
        ("How do I track my order?", "Use the 'My Orders' option in the bot menu to check your order status anytime.", 5),
        ("Are these products safe?", "All products are prescription-grade peptides and compounds intended for use within medically supervised programmes. Please consult your healthcare provider before starting any new treatment.", 6),
        ("How should I store the products?", "Most peptides should be stored refrigerated at 2-8C. Do not freeze. Protect from direct sunlight. Specific storage instructions are provided with each product.", 7),
    ])

    await db.commit()
    await db.close()
